services:
  app-dev:
    container_name: notion-app
    build: 
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    restart: always
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - MASTER_DB_ID=${MASTER_DB_ID}
      - NOTION_VERSION=${NOTION_VERSION}


  # tests: 
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /usr/app/node_modules
  #     - .:/usr/app
  #   stdin_open: true
  #   tty: true
  #   command: ["npm", "run", "test:watch"]

  nginx: 
    container_name: nginx-notion
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 3000:3000