services:
  notion-api:
    image: aafu6296/notion-api:latest
    hostname: api
    restart: always
    environment:
      - NOTION_API_KEY=$NOTIdockerON_API_KEY
      - MASTER_DB_ID=$MASTER_DB_ID
      - NOTION_VERSION=2022-06-28

  earendel-app:
    image: aafu6296/web-app:latest
    hostname: earendel-app
    restart: always

  nginx: 
    image: aafu6296/nginx:latest
    mem_limit: 128m
    restart: always
    hostname: nginx
    volumes:
      - /etc/pki/tls/certs/:/etc/pki/tls/certs/
    ports:
      - '80:80'
      - '443:443'