FROM node:23-alpine3.21 AS nestbuilder

WORKDIR '/usr/app'

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

## /usr/app/build <- all the stuff we care about

FROM nginx
COPY --from=nestbuilder /usr/app/build /usr/share/nginx/html