name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t afaqahmad/notionsync-test -f Dockerfile.dev .
      - run: docker run -e CI=true afaqahmad/notionsync-test npm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: notionsync
          environment_name: Notionsync-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-203918860171
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

