name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t afaqahmad/notionsync-test -f Dockerfile.dev .
      - run: docker run -e CI=true afaqahmad/notionsync-test npm run test
